name: movtirz
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.4.0
  get: 4.6.6
  shimmer_animation: ^2.2.1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  tmdb_api: ^2.2.0
  like_button: ^2.0.5
  carousel_slider: ^5.0.0
  dio: ^5.5.0+1
  gif: ^2.3.0
  flutter_svg: ^2.0.10+1
  get_storage: ^2.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
